"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _product_grid from './product-grid.bones.json'

configureBoneyard({"color":"#efe4d2","darkColor":"#241a1b","animate":"shimmer","shimmerColor":"#f8f1e5","darkShimmerColor":"#302324","speed":"1.8s","transition":300})

registerBones({
  "product-grid": _product_grid,
})
